### ISSUE TITLE
ArgumentNullException when git name or email not set

### ISSUE THREAD

**Issue by geluk** [geluk/pass-winmenu#100]
> 
> It might be my fault, but with the new exe i get this:
> ArgumentNullException (Value cannot be null. Parameter name: author)
> 
> Everything worked fine with the latest version
> I just reinstalled my windows yesterday
> Setup everything from clean

_Originally posted by @xxxcrow in https://github.com/geluk/pass-winmenu/issues/97#issuecomment-939500947_

**Comment by xxxcrow** [comment]
> 
> 
> @xxxcrow: I suspect you haven't set your `user.email` and `user.name` configuration variables yet. If that's the case, you can work around the issue by setting them:
> 
> ```
> git config --global user.name <name>
> git config --global user.email <email>
> ```
> 
> If not, can you explain what you did when you got the error?

I actually thought ```git config``` should solve the issue, but it didn't
Firstly i had "UriFormatException" error
I knew i didn't set user.name/user.email for git
In the issue "UriFormatException" you sent a new exe file that should solve it
But with the new version a new exception showed "ArgumentNullException"
After you suggested ```git config --global user.name <name> git config --global user.email <email>```
And... it shows the same "ArgumentNullException"

**Comment by geluk** [comment]
Fixed in 1.12.1
