### ISSUE TITLE
"Open Shell" command fails for users with apostrophe in username

### ISSUE THREAD

**Issue by Sgt-Nukem** [geluk/pass-winmenu#109]
With a username (and thus profile directory) like `xxxxxxit 'k'` the "Open Shell" command which opens PowerShell *with correct GPG path* is unusable:

<img width="854" alt="image" src="https://user-images.githubusercontent.com/4144388/195377226-767bf1f0-6fce-4c63-85cb-0a742eb2fd23.png">

Parsing of the path to the GPG executable stops at the first occurence of an apostrophe. This needs to be escaped.

**Comment by geluk** [comment]
Hi @Sgt-Nukem, I have created a new build in which the arguments to the `gpg` command are escaped properly. Can you check if this solves your issue?

You can download the executable here: https://ci.appveyor.com/api/buildjobs/0vttj2pb796d0ofy/artifacts/pass-winmenu%2Fbin%2FRelease%2Fpass-winmenu.exe

**Comment by Sgt-Nukem** [comment]
> Hi @Sgt-Nukem, I have created a new build in which the arguments to the `gpg` command are escaped properly. Can you check if this solves your issue?

I just did the regular upgrade to 1.13.1 - but now it won't start at all: c.f. issue #110

**Comment by Sgt-Nukem** [comment]
> Hi @Sgt-Nukem, I have created a new build in which the arguments to the `gpg` command are escaped properly. Can you check if this solves your issue?

The "Open Shell" command now works as expected since re-release of 1.13.1 - thanks.
