### ISSUE TITLE
(Not a bug) PSA: AutoHotKey script to focus the password entry dialog

### ISSUE THREAD

**Issue by Sgt-Nukem** [geluk/pass-winmenu#112]
I made this AHK script to focus the "Pinentry" dialog every time it appears, so you can just type your password without using your mouse or ALT-Tabbing twice.

Just install AutoHotKey and put the text below in some `password-focus.ahk` file or so, then move it into the `shell:startup` folder.

```
#SingleInstance, Force
SendMode Input
SetWorkingDir, %A_ScriptDir%


; When a new 'Pinentry' window spawns (used by pass-winmenu which in turn uses the pass password manager) activate it and give keyboard focus for PIN entry
Loop
{
	WinWait, Pinentry,,
	WinActivate
}

```

**Comment by geluk** [comment]
Thanks for the contribution! For anyone else running into this issue, note that you can also use `gpg4win` instead. It supplies a different pinentry application which seems to work better in my experience.
