### ISSUE TITLE
Request for a new snippet management application utilizing Pass-Winmenu interface

### ISSUE THREAD

**Issue by daohx** [geluk/pass-winmenu#124]
Hi,

I really enjoy using Pass-Winmenu. Would it be possible for you to develop another application for managing code snippets, utilizing the same menu without encryption? Ideally, this new app would be able to read snippets directly from markdown files.

Thanks

**Comment by geluk** [comment]
Hi, I am glad you enjoy using pass-winmenu! Unfortunately I don't have enough time to maintain another application myself. However, because the code is open source, you or anyone else is free to copy it and modify it to whatever purpose you like.
