### ISSUE TITLE
Add delay option in config before program checks for the path of password store

### ISSUE THREAD

**Issue by szero** [geluk/pass-winmenu#126]
Hello, so when using samba share path for the password store sometimes on system startup your program errors out that no such password folder exists. Adding some delay on startup would be easy fix.

**Comment by szero** [comment]
![winpassmenu-error](https://github.com/geluk/pass-winmenu/assets/15748979/42676780-6e54-4a87-966d-0f0ad4558658)
Just wanted to leave the exact error that causes program to fail (mildly annoying since it closes the program and you have to restart it manually). Great software otherwise, allowed me to migrate all my passwords to pass, cheers.

**Comment by geluk** [comment]
Hi, I think the problem should be resolved, but I forgot to follow up with you. Can you check with [this build](https://ci.appveyor.com/api/buildjobs/s8k15f9v1930nu6y/artifacts/pass-winmenu%2Fbin%2Fpass-winmenu.zip) if it resolves your issue?

**Comment by szero** [comment]
Yo, thanks for getting around fixing that, I guess you made it so it only checks if the path of the pw store is valid only when you query the program with key combination? Works perfect and if the path is not valid program doesn't quit anymore.
