### ISSUE TITLE
(question) How can I change my master password?

### ISSUE THREAD

**Issue by 1thz** [geluk/pass-winmenu#128]
Hi, thank you making this available in windows

If my understanding is correct, the passwords that I had saved are encrypted using the GPG private key. If I wish to change my master password, I would have to generate a new GPG key pair but this new keypair wouldn't work with my existing password store, correct? 

If I wish to change my master password, how could I do so?

**Comment by willpower232** [comment]
You can change the pass phrase on a GPG key, if you haven't encrypted the files with multiple keys already (not sure if it is a feature of pass but it is a feature of GPG), then you would lose access if you lost your current key file.

https://www.cyberciti.biz/faq/linux-unix-gpg-change-passphrase-command/
