### ISSUE TITLE
Unhandled exception when calling "About" from SysTray context menu

### ISSUE THREAD

**Issue by Sgt-Nukem** [geluk/pass-winmenu#133]
Cause: `"%USERPROFILE%"` consists of spaces and single quotes (c.f. issue #109)

A bit weird this time because it is used as working directory for opening a browser only:

`An error occurred trying to start process 'https://github.com/geluk/pass-winmenu#readme' with working directory 'C:\Users\xxxxxxit 'k'\.bin\pass-winmenu'. The system cannot find the file specified.`

**Comment by geluk** [comment]
Thanks for the bug report, should be fixed now. You can download a test build here: https://ci.appveyor.com/api/buildjobs/y58ruf73mge62cl0/artifacts/artifacts%2Fpass-winmenu.exe

**Comment by Sgt-Nukem** [comment]
> Thanks for the bug report, should be fixed now. You can download a test build here: https://ci.appveyor.com/api/buildjobs/y58ruf73mge62cl0/artifacts/artifacts%2Fpass-winmenu.exe

That fixed it. Thanks.
