### ISSUE TITLE
pass-winmenu don't decrypt password properly (empty file)

### ISSUE THREAD

**Issue by majvax** [geluk/pass-winmenu#135]
I imported my gpg key, up the trust using the shell built-in pass-winmenu.
The problem is that when decrypting the file to put it in my clipboard, I got nothing.
When editing the password file, it shows an empty file:

![image](https://github.com/user-attachments/assets/87b4df42-e970-4cc5-ad36-1c0a3b5ca0f8)

However, the file should contain my password, since I sync it with github from my phone
![image](https://github.com/user-attachments/assets/2114d914-7d36-429c-88a9-60458f5b10d2)

The file is detected so it's not a problem from the path, I don't really know...

![image](https://github.com/user-attachments/assets/4605f5f5-f93a-4bb6-89af-d7fa09c29646)

**Comment by willpower232** [comment]
did you get the gpg version or the non-gpg version of pass-winmenu?

depending on where you imported your key, you may also need to edit the config file to point to the right place

**Comment by majvax** [comment]
non-gpg version
I mean i read the config file and didn't found anything interesting imo but I may didn't see a settings or smth.
I follow the readme to configure pass-winmenu (for importing the key)

**Comment by willpower232** [comment]
I always change `gnupghome-override` because my directory is in a non default place and you would need to make sure that the `gpg-path` is set correctly for wherever you are running it from

![image](https://github.com/user-attachments/assets/4532ddda-d1f7-44ea-ac99-14c179c85d7d)

**Comment by majvax** [comment]
Yeah, gpg-path is set correctly I think. 
I don't really understand why should i override the gpg home (I don't use oyher gpg homedir) I still specified the same directory as you.


I reimported the key
![image](https://github.com/user-attachments/assets/73f7d859-aeee-4fc5-92bf-e5fd6b4891e0)
![image](https://github.com/user-attachments/assets/dd064592-47b0-4e14-97ee-332c14ad3c24)


but still, the clipboard is empty and same when editing password file
![image](https://github.com/user-attachments/assets/4d4ffba6-a273-4e82-a754-b1c2cfad2a42)

This is my config:
![image](https://github.com/user-attachments/assets/def41b09-e8a0-4ced-ab6e-fc5cedaaa006)
(I added gpg bin to my path env but that change nothing to the problem)

**Comment by geluk** [comment]
Are you sure you didn't encrypt an empty file? What is the output of running `gpg --decrypt github/personnal.gpg` in the builtin password shell? (Make sure to censor the password if it's in there somewhere!)

**Comment by willpower232** [comment]
You would probably also need to restart the app if the config file changed, presuming your gnupg is indeed in your home directory, I think the default path is fine if thats where your folder is. I just copy mine out of linux and dump it there since I use the gpg version of pass-winmenu.

**Comment by majvax** [comment]
It doesn't output anything

![image](https://github.com/user-attachments/assets/70cbd36c-5d04-4f12-b787-4c5c1bfe1e6a)

But I can assure that it contains something since on my phone I can see the password when using pass show github/personnal

![image](https://github.com/user-attachments/assets/d92cc0cb-a8d2-4553-9cd8-1a509c73f7bd)

git status indicated that i'm up to date with the repo so It shouldn't be a problem from an empty file

I didn't mention but I already restart the app everytime I made some change to the config

**Comment by majvax** [comment]
To provide further information, I fix the issue by installing GnuPG, removing the old pass-winmenu and installing the nogpg version. I imported the key and now, It work flawlessly. Maybe there is a problem in the gpg version distributed with the app ?

**Comment by geluk** [comment]
Glad to hear you were able to fix it. In my experience the version distributed with the app works fine, but one thing that I've seen before is that when you have two different versions of GPG, they can sometimes conflict. This can happen because on first launch GPG will start `gpg-agent`, a background process that handles part of the cryptographic operations. If conflicting versions of GPG and gpg-agent try to communicate (for instance, because you have a local GPG installation different from the one bundled in pass-winmenu) decryption fail or hang without a clear error message.

If you want we can investigate this further but since it looks like a problem with GPG, I'm also fine with just closing this issue and reopening it if it occurs again.

**Comment by majvax** [comment]
The thing is that I don't have two different versions of gpg, this is precisely why I didn't choose the no GPGversion in the first place, because I wanted pass-winmenu to work out of the box. (I later installed the version shipped without GPGand installed the GPG myself).

I'm also fine just closing the issue since I don't have any knowledge regarding GPG.
