### ISSUE TITLE
Cannot decrypt the password

### ISSUE THREAD

**Issue by micuele** [geluk/pass-winmenu#137]
Pass-winmenu cannot find the secret key to decrypt the passwords

**Comment by micuele** [comment]
You must edit the pass-winmenu.yaml.
Write on the cmd `where.exe gpg` and copy the path on `gpg-path: '[path]'`.
gnupghome-override should be `C:\Users\<YourUsername>\AppData\Roaming\gnupg\` .

This worked for me.

**Comment by willpower232** [comment]
Yeah windows likes to keep things in weird places so I think they're both in different places a lot of the time.

P.S. feel free to close the issue if you don't need any more help :pray:
