### ISSUE TITLE
Add passphrase

### ISSUE THREAD

**Issue by majkinetor** [geluk/pass-winmenu#27]
I use passprhase for some stores instead of gpg key. Passmenu works with it but it pops up passphrase each time.

Passprhase should be taken from config or environment var or cached.

**Comment by geluk** [comment]
I looked into this, if you set `gpg-agent.config.allow-config-management` to `true`, it will cache your passphrase for the time configured in `keys.default-cache-ttl` and `keys.max-cache-ttl` ([see here](https://github.com/geluk/pass-winmenu/blob/241490952a96b231047feed33928b3295a4b6fdf/pass-winmenu/embedded/default-config.yaml#L157)).

**Comment by majkinetor** [comment]
Thanks, didnt know that.
