### ISSUE TITLE
passphrase dialog has no focus when displayed

### ISSUE THREAD

**Issue by mrembisz** [geluk/pass-winmenu#51]
First of all thanks for this nifty tool. I am using this now and I like it a lot. Got one minor issue though. When I am prompted for passphrase after selecting my file, window has no focus. I have to click the dialog first before I can start typing my password.

**Comment by geluk** [comment]
Thanks! This is indeed an issue that I'm aware of, although I have not yet been able to track down why this happens (it seems to be mostly random as far as I can tell). I'll look into this a little further.

**Comment by JarnoStark** [comment]
I have the same issue while using the tool. I startet du use first the only Passwort Copy Hotkey to type in my passphrase for one time, and then use the Auto Fill Hotkey. Its just one more Hotkey so its not that bad.

Is it possible that the window hasnt focus because of multible Monitors? Just an Idea...

**Comment by geluk** [comment]
I have been looking into it further, and I came to the same conclusion that it only occurs on a multi-monitor setup. For whatever reason, Pinentry (the application used by GPG to prompt for passphrases) does not place itself in the foreground properly. I actually wrote a helper method to see if I could make pass-winmenu force it to the foreground (using a direct call to [SetForegroundWindow](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow)) which still fails (you'll see a log message saying "Failed to send pinentry window to foreground" whenever it happens).

It seems like Windows does not allow the window to be moved to the foreground, but it's still unclear to me why that is.

**Comment by gnugnug** [comment]
For me it is the other way round with v1.11.1: When 2 monitors are connected, the passphrase dialog has focus. With only 1 monitor, the window is displayed in the foreground, but has no focus.

**Comment by geluk** [comment]
One solution I've found to work so far is to switch to Gpg4Win, which uses a different pinentry window where this issue is not present.

**Comment by mrembisz** [comment]
Works perfectly. Also the window shows up immediately, with stock gpg it took like 10 seconds to appear. Thanks a lot!
