### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by duhruh** [geluk/pass-winmenu#52]
Wondering if you could cut a new release, or provide an easy way to compile the project. It's been a couple of commits since the last release, and i believe some of the issues i'm facing have been fixed on master.

**Comment by geluk** [comment]
You can download a release build from CI if you go here: https://ci.appveyor.com/project/baggykiin/pass-winmenu/history

You can then choose the commit you want a build for, and click on 'Artifacts'. You can then download the release there. For the most recent release, for instance, you can find them here: https://ci.appveyor.com/project/baggykiin/pass-winmenu/builds/27070842/artifacts

Let me know if that works for you, if it fixes your issues I'll create a new release for it.

**Comment by geluk** [comment]
v1.10 is out now, so I'll go ahead and close this.
