### ISSUE TITLE
Arrange window in size and position

### ISSUE THREAD

**Issue by 0xphk** [geluk/pass-winmenu#56]
First of all, 

thanks for this awsome tool, it's fantastic to use one central pass git store truly cross-platform. 
I use it regularly since 1.7 :+1: 
This is just a question, is there a way of modifying the window behaviour in size and position?
At least free positioning would be really nice.

Thanks

**Comment by geluk** [comment]
Thanks for the kind words!
You can alter the default positioning of the window in the configuration file, it's all the way at the bottom. Here's the location in the default configuration file for your reference:
https://github.com/geluk/pass-winmenu/blob/master/pass-winmenu/embedded/default-config.yaml#L328
Also take note of `follow-cursor` a bit higher up, which determines the screen on which pass-winmenu opens.

Is that what you mean? Or would you like to be able to drag and drop the window around when it is opened?

**Comment by 0xphk** [comment]
Thought more about free dragging but I will look into the mentioned settings as I wasn't aware of offset and width/height. Thank you

**Comment by geluk** [comment]
I'll close this now. If, in addition to the settings I mentioned, you would find it useful to be able to move and resize the window by dragging, let me know, and I'll reopen the issue.
