### ISSUE TITLE
Notification No Longer Showing Up

### ISSUE THREAD

**Issue by Aetylus** [geluk/pass-winmenu#59]
I don't know if this was related to a Windows update, but at some point I noticed the notification that the password was copied to clipboard was no longer showing up. I've verified the setting is enabled in my `pass-winmenu.yaml` file, and have tried to uninstall and reinstall pass-winmenu as well. I'm not seeing anything immediately obvious to me in the logs either that would point to a problem.

I am currently on Windows 10 Enterprise 1903.

**Comment by geluk** [comment]
I ran into this issue a while ago as well. After looking into it a bit more I discovered that Windows had disabled notifications for several applications, including pass-winmenu. I had to manually re-enable them by going to Settings -> System -> Notifications & actions.

![image](https://user-images.githubusercontent.com/1516985/77917499-eb834480-729a-11ea-8be9-3e4e3285ebac.png)

Can you check if that is what happened in your case as well?

**Comment by Aetylus** [comment]
That was it exactly, thanks! I'm guessing Windows decided to automatically disable it for whatever reason.
