### ISSUE TITLE
Could add option on startup to specify configuration location

### ISSUE THREAD

**Issue by leetking** [geluk/pass-winmenu#60]
I want to startup pass-winmenu when I login, and according to this thread https://www.akadia.com/services/windows_registry.html, add a registery like this `pass-winmenu: C:\Users\ltk\scoop\apps\pass-winmenu-nogpg\current\pass-winmenu.exe`. but when I login, I face a error which means `cannt generate configuration and log file at C:\Windows\System`. For this I guess the reason is pass-winmenu just try to find configuration at _work directory_ so it cannt find the configuration correctly.

I have a little appeal that could add a startup option to specify configuration locatioin.

P.S.
- I install pass-winmenu (`pass-winmenu-nogpg`) via [scoop](https://scoop.sh/) -- a command-line installer for Windows
- the version of pass-win is 1.10.1

**Comment by geluk** [comment]
Pass-winmenu has an option to run on startup. You can right click the icon in the notification area and select `Start with Windows` to enable this feature.

Hopefully that will fix your problem, but separately from that, I do think it would be good to allow loading the configuration file from a different location, which would probably best be done using an optional argument. Something like `--config-location C:/some/path`.

**Comment by leetking** [comment]
Please forgive my mistake 😢. I have tried this fantastic option, It works perfectly for me. Thanks your work to create a awesome software.
Since it has a feature of auto startup, maybe we don't need option to specify configuration.

**Comment by geluk** [comment]
No worries! Glad I could help. I do think it would be good to have the option to specify the location of the configuration file, so I'll probably still add that.

**Comment by leetking** [comment]
It's fine. Thanks a lot.

**Comment by geluk** [comment]
Implemented as of [v1.11](https://github.com/geluk/pass-winmenu/releases/tag/v1.11).
