### ISSUE TITLE
Program Crashes at Launch--with Error Message

### ISSUE THREAD

**Issue by kirkzp** [geluk/pass-winmenu#62]
Hi,
I am trying to get up and running with this.  Downloaded the latest version today, with GPG included.  But, the program won't launch.  Or, more accurately, the program does start but a GUI never shows up.  Instead, I get the error message that there are no stored passwords (attached).  The error message can be dismissed, but nothing else comes up.  However, if I launch task manager, it does appear that a process is continuing to run, but there is no way for me to interact with it.  FYI, I am on Windows 7 with all patches thru EOL and .NET version 4.8 running.  I'd love to test this out but ...
![StartFail](https://user-images.githubusercontent.com/66496505/83925129-42921380-a73b-11ea-9b7d-7850fbb793db.png)

**Comment by geluk** [comment]
Hi, thanks for trying it out! This error message indicates that pass-winmenu couldn't find your any GPG keys, which you need in order to encrypt your passwords. 

Do you already have a GPG key? If not, you'll need to generate one. Check the [readme](https://github.com/geluk/pass-winmenu#setting-up-gpg) for instructions.

If you do, pass-winmenu couldn't find it. This normally should only happen if your GPG keys are stored in a non-standard location. I don't think this is the case, but it's possible. Let me know if it is, and I'll be able to help you further.

**Comment by kirkzp** [comment]
Sorry, maybe I wasn't clear.  I don't have GPG.  I don't have any keys.  I want to use your full version w/ GPG to create my master key.  

Here are your instructions:
>If you already have a GPG key, you can skip this step and go to 'creating a new password store'. If >you've never used GPG before, you can generate a new key. Start pass-winmenu, right click the >key icon in the notification area, and click Open shell.

But I cannot do any of these things b/c the program just crashes immediately on boot.  
The VERY FIRST TIME I tried running it, I got the error message that it could not find my key folder.  So, I created that folder, which is empty.  But, now it crashes with the 'no keys' error.  

I am trying to do a first-time, fresh install, and I want to use pass-winmenu to do everything.  This should be the simplest case, no?  Please let me know what I need to do differently to get a program window up and running.  

Thanks!

**Comment by geluk** [comment]
I understand now, I guess this message could be a bit clearer in this case. It's not a crash, it's just a warning that gets shown when no GPG keys are found. Normally this is an error situation, but of course it's expected when you're setting up a completely new environment. I've wanted to create a guided setup for this situation for a long time, though I never got around to it.

Anyway, regarding your situation, I would expect pass-winmenu to be running (it won't shut down after displaying this message), can you check the notification area for a key icon? 
![image](https://user-images.githubusercontent.com/1516985/83957159-e4158400-a865-11ea-80f7-58d4bb0b973e.png)

You'll probably need to expand the overflow menu to find the icon.
If it's neither there nor in the overflow menu, then that's definitely an error. If it's there, you can right click it and click 'Open shell', and continue with the setup guide from there.

**Comment by kirkzp** [comment]
Thanks so much for the detailed and timely advice.  I did find the icon (after changing default Windows behavior to "show icon and notifications" from "show notifications only".  And, I launched the powershell and GPG.  But, I couldn't key through the key-gen process.  Screenshot shows errors.  First there was a "filename too long issue" then a "no agent running issue".  Perhaps the first caused the second?  I feel I am getting close; any advice to get me the rest of the way would be most appreciated.  

![PROGRESS](https://user-images.githubusercontent.com/66496505/84174644-b5e59f00-aa33-11ea-8892-93f25e67d337.png)

**Comment by kirkzp** [comment]
OK.  I moved the pass-winmenu file closer to $HOME and got through GPG generation.  I need to get back to work, so it'll be a bit before I get to make some password files and fully test this, but I am optimistic.  No action required right now---I'll post further here to let you know how things go and close issue if appropriate.  Thanks again.

**Comment by kirkzp** [comment]
Cool.  I have everything working now.  Thanks for the development and the support--donation/beer shortly on its way.  Just something to note.  It was a little complicated on my machine (Win 7).  Ultimately, the correct answer was, as suggested, to right click the icon in the tray and use it to open shell.  However, I did need to manually create the password-store directly separately and first.  Before I created an empty store, the program would simply crash on launch.  This meant I couldn't use the system-tray icon as a departure point.  However, once I created the store, the behavior was as you described---error message followed by running in the background.  The maximum pathlength to GPG is clearly THEIR limitation, not yours, so no worries there.  Best, K

**Comment by geluk** [comment]
> Before I created an empty store, the program would simply crash on launch.

That's almost certainly a bug, I'm going to test this and see if I can do anything to fix that.

> The maximum pathlength to GPG is clearly THEIR limitation, not yours, so no worries there. 

I'm still glad you brought this to my attention. I'm going to check this out as well, if it's easy enough to run into it I might end up documenting it somewhere.

Thank you for your testing! As I mentioned, I've wanted to look into smoothing out the whole first-run experience, and your feedback on this is very helpful for this.
