### ISSUE TITLE
show menu on left-click of system tray icon, not just right-click

### ISSUE THREAD

**Issue by slippycheeze** [geluk/pass-winmenu#67]
pass-winmenu doesn't do anything when you left-click the system tray icon; there really isn't much that'd make sense to have happen.

given that the right-click menu is the most likely mouse-driven thing to do, it'd make sense to show that menu regardless of which button was used. :)

**Comment by geluk** [comment]
Sensible suggestion, thanks! I've implemented it and will include it in the next release.

**Comment by geluk** [comment]
Implemented as of [v1.11](https://github.com/geluk/pass-winmenu/releases/tag/v1.11).
