### ISSUE TITLE
Allow encrypting to multiple GPG IDs

### ISSUE THREAD

**Issue by bratekarate** [geluk/pass-winmenu#85]
With UNIX passwordstore it is possible to encrypt entries to multiple GPG IDs. pass-winmenu on the other hand only uses the first key it finds. This causes kind of a mess when writing from Windows and Linux devices, as some entries will be encrypted to multipel and others only to one ID. Would be great if pass-winmenu would also respect an array of GPG IDs and uses them all as recipient, just as UNIX passwordstore does.

**Comment by geluk** [comment]
Can you elaborate a bit on how your GPG IDs are structured?
The method pass-winmenu currently uses should be the same as used by pass.
It starts at the directory of the password file you selected, and looks for a `.gpg-id` file. If it doesn't find one, it keeps walking up the directory tree until it reaches the root of your password store.
All ID's found in the first file are selected as recipients.

**Comment by bratekarate** [comment]
Hm, maybe my issue is not related to multiple keys at all. I use an env variable `PASSWORD_STORE_KEY='KEY1  KEY2'`. Could it be that this env variable is not supported in pass-winmenu?
