### ISSUE TITLE
Respect PASSWORD_STORE_KEY environment variable

### ISSUE THREAD

**Issue by bratekarate** [geluk/pass-winmenu#86]
UNIX passwordstore accepts -- among others -- the environment variable `PASSWORD_STORE_KEY`, which may hold one or multiple space separated gpg key IDs/email addresses. This variable overrides the keys specified in `.gpg-id` (if it exists). 

It would be great if pass-winmenu would respect this variable as well. It makes it easier to hide the recipients when working with the `hidden-recipients` option in gpg and using a cloud service like Nextcloud. The `.gpg-id` file can be ommitted this way, as nextcloud has no easy way to ignore files on all clients.

On another note, even if unrelated, is it possible to customize the gpg options, such as `PASSWORD_STORE_GPG_OPTS` in pass for UNIX? To add `hidden-recipients`.

**Comment by geluk** [comment]
Implemented in [v1.12](https://github.com/geluk/pass-winmenu/releases/tag/v1.12).
