### ISSUE TITLE
Wrong GPG Key used for signed commits

### ISSUE THREAD

**Issue by sbu-WBT** [geluk/pass-winmenu#88]
I have multiple gpg keys configured for multiple git(hub) accounts.

I've set additionally the signingkey in the individual repo config but this didn't help.

Committing with the commandline works fine and uses the correct key.

**Comment by geluk** [comment]
That's odd, it is supposed to take the `repo.signingkey` from the repository configuration, escalating to global settings if it does not exist. I'm going to check if I can reproduce this.

**Comment by sbu-WBT** [comment]
After a bit of debugging I came to the result, that this line has the correct key for signing:
https://github.com/geluk/pass-winmenu/blob/87c5dd16e500acf817d9db9f73d36a2059eef8c9/pass-winmenu/src/ExternalPrograms/Git/Git.cs#L120

But the determined key is never used in the `Sign` method:
https://github.com/geluk/pass-winmenu/blob/87c5dd16e500acf817d9db9f73d36a2059eef8c9/pass-winmenu/src/ExternalPrograms/Gpg/GPG.cs#L83-L89

Maybe that's the problem that the specified key isn't used?

**Comment by geluk** [comment]
Thanks for looking into it! You're absolutely right, I am not sure how I missed that when I wrote it. It works fine when GPG happens to select the correct key, which I suppose is why no one has discovered this earlier.

**Comment by sbu-WBT** [comment]
This is also fixed, thank you!
