### ISSUE TITLE
pass-winmenu 1.11.1 does not sign commits

### ISSUE THREAD

**Issue by gnugnug** [geluk/pass-winmenu#94]
I'm using pass-winmenu v1.11.1 and have the following (global) git config:

$ git config --list
user.email=<emailaddress>
user.signingkey=<emailaddress>
commit.gpgsign=true
gpg.program=C:/Program Files (x86)/gnupg/bin/gpg.exe

Unfortunately when adding or editing a password entry pass-winmenu creates an unsigned commit. This has worked before with the Nightly-version from https://github.com/geluk/pass-winmenu/issues/69#issuecomment-725377690_ so I'm unsure what causes this problem.

**Comment by gnugnug** [comment]
Thank you, this fixes the issue! Gitlab accepts the signature without CR again as valid.

**Comment by geluk** [comment]
Fixed in [v1.12](https://github.com/geluk/pass-winmenu/releases/tag/v1.12).
